### PR TITLE
Allow falsy values like 0, false, empty string to be allowed values f…

### PR DESCRIPTION
**Pull request by kchobantonov**
…or enums

Example schemas

```
{
  "type": "object",
  "properties": {
    "areYouTall": {
      "type": "boolean",
      "oneOf": [
        {
          "const": true,
          "title": "Yes"
        },
        {
          "const": false,
          "title": "No"
        }
      ]
    }
  },   
  "required": [
    "areYouTall"
  ]
}
```

```
{
  "type": "VerticalLayout",
  "elements": [
    {
      "type": "Control",
      "scope": "#/properties/areYouTall"
    }
  ]
}
```

### CODE REVIEW

**Comment by kchobantonov** [comment]
@yaffol can you take a look into the ArrayLayoutRenderer that you have changes because this build fails that on line 458 there is no this.data - perhaps the line should be 
        data: this.control.data,
?

@sdirix  can you review this PR - this allows enums with falsy values to be used correctly otherwise it clears the input when such are selected. I was thinking about the same perhaps for the strings to eventually allow empty string for example but since the text control always have an empty value when it is cleared then we will not be able to remove properties for those types but for enums that are renders with dropdowns and etc. it is easy to implement and use those falsy values as well

**Comment by kchobantonov** [comment]
the above issue with the array renders is fixed in PR https://github.com/eclipsesource/jsonforms-vuetify-renderers/pull/76

**Comment by sdirix** [comment]
I'll check the code soon! Thanks for the contribution :heart:

**Review by lucas-koehler — APPROVED** [review]
Thanks again for the contribution :)
Code changes look good to me and your example works well

**Pull request merged**
