### PR TITLE
fix: fix radio binding and use @update:modelValue instead of @change

### PR DESCRIPTION
**Pull request by Toilal**
Radio group is broken, and i've removed all @change event handlers in favor of @update:modelValue.

### CODE REVIEW

**Comment by sdirix** [comment]
Thanks for the update

**Review by sdirix — APPROVED** [review]

**Comment by sdirix** [comment]
@Toilal thank you very much for the contribution :heart:

**Comment by Toilal** [comment]
Great, thanks @sdirix. Is it possible to release on npmjs ?

**Comment by sdirix** [comment]
Hi @Toilal, yes! we plan to release `@jsonforms/vue-vuetify@3.2.0.preview` this week, probably on Friday.

**Comment by sdirix** [comment]
Released as `@jsonforms/vue-vuetify@3.3.0-preview.0`

**Pull request merged**
