### PR TITLE
Improve rendering for nested objects

### LINKED ISSUE #30: Wrap only the first level of nested objects with a border
Every nested object within the schema, when it's rendered, is in a border.

This gets visually very busy.

A good balance is to add a border to only the first level of nesting, thereafter nested groups of fields are differentiated by indentation and padding. The border is controlled by the vuetify `elevation` setting.

### PR DESCRIPTION
**Pull request by sdirix**
Nested objects are now rendered indented without any additional
elevation. The indentation stops at level four. This leads to
a less cluttered UI for heavily nested objects.

Extends the group renderer to being able to support a 'bare' UI
without elevation and borders. Also supports left-aligning them
to prevent further indentation when necessary. These two UI
Schema options are used by the object renderer to render nested
objects appropriately.

Adds a nested object example to demonstrate the new behavior.

Fixes #30

### CODE REVIEW

**Comment by sdirix** [comment]
@yaffol seems like my CSS customization in the object renderer are not applied correctly when the example application is built. It works for me when just `npm run example:serve` it. I'll investigate.

**Comment by sdirix** [comment]
> @yaffol seems like my CSS customization in the group renderer are not applied correctly when the example application is built. It works for me when just `npm run example:serve` it. I'll investigate.

Fixed the issue. With the last release I accidentally decoupled the example app with the library. Therefore the example app always used the previous release instead of the local version of the Vuetify renderers. Did not notice on my machine as my local state was still correct (was not yet decoupled for me).

**Comment by yaffol** [comment]
Looks good for objects nested in an object. Objects within arrays seem to still be getting borders irrespective of nesting level.

image
image

**Comment by yaffol** [comment]
Here is an example schema that reproduces the array/nested behaviour

`{
  "title": "Example nested array",
  "type": "object",
  "properties": {
    "anArray": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "nestedObject": {
            "type": "object",
            "properties": {
              "loc": {
                "type": "string"
              },
              "toll": {
                "type": ["string", "null"]
              },
              "message": {
                "type": ["string", "null"]
              }
            },
            "required": [
              "loc"
            ]
          },
          "loc": {
            "type": "string"
          },
          "toll": {
            "type": ["string", "null"]
          },
          "message": {
            "type": ["string", "null"]
          }
        },
        "required": [
          "loc"
        ]
      }
    }
  }
}
`

**Review by yaffol — APPROVED** [review]
Approve. Like the use of provide to pass the nesting level :)

**Pull request merged**
