### PR TITLE
provide template renderer - fixes #85

### LINKED ISSUE #85: provide template renderer
Provide a new template renderer that utilized the vue-template-compiler without the jsonforms-vuetify renderers library to have a direct dependency on the vue-template-compiler - only when the application uses the advanced renderers then the final application will include the vue-template-compiler

### PR DESCRIPTION
**Pull request by kchobantonov**
Provide a general layout renderer that is based on vue templates. The template renderer can be extended to recognize new components, data, etc.

Also provide Template renderer and Slot renderer that are used with  uischemas - for work with that feature a new name property was introduced to UISchemaElement (as new property - not changing the jsonforms core definition which at some point will be nice to be moved there - e.g. able to name the UISchemaElements)

### CODE REVIEW

**Comment by kchobantonov** [comment]
@sdirix @lucas-koehler here is the rewritten template-renderer but this time it does not depend on the vue-template-compiler directly which means that if you do not want to use it then you won't be having the target JS file enlarged with the vue-template-compiler

At the moment the example application is using the advancedVuetifyRenderers that included this new renderer - the code is in [example/src/store/modules/app.ts](https://github.com/eclipsesource/jsonforms-vuetify-renderers/blob/ed1216844499244f27c5bb8a2605865f7988c31e/example/src/store/modules/app.ts)

If you build the example application under the dist/js folder you will see the npm.vue-template-compiler...js dependency - but if you change this code in app.ts

```
// import {
//   createAjv,
//   extendedVuetifyRenderers as vuetifyRenderers,
// } from '@jsonforms/vue2-vuetify';

// async load of compiler to enable code split
const compileToFunctions = () =>
  import('vue-template-compiler').then((module) => {
    const { compileToFunctions } = module;
    return compileToFunctions;
  });
import { createAjv, advancedVuetifyRenderers } from '@jsonforms/vue2-vuetify';
const vuetifyRenderers = advancedVuetifyRenderers(compileToFunctions);
```

to this 

```
 import {
   createAjv,
   extendedVuetifyRenderers as vuetifyRenderers,
 } from '@jsonforms/vue2-vuetify';

// async load of compiler to enable code split
//const compileToFunctions = () =>
// import('vue-template-compiler').then((module) => {
//    const { compileToFunctions } = module;
//    return compileToFunctions;
//  });
// import { createAjv, advancedVuetifyRenderers } from '@jsonforms/vue2-vuetify';
// const vuetifyRenderers = advancedVuetifyRenderers(compileToFunctions);
```

then you won't see the npm.vue-template-compiler dependency and the demo page [template-renderer](https://deploy-preview-86--jsonforms-vuetify-renderers.netlify.app/#/example/template-layout) won't show all elements and will say that it can't find a renderer.

**Comment by kchobantonov** [comment]
Fixes #85

**Comment by kchobantonov** [comment]
@sdirix @lucas-koehler this PR is ready - I have added additional TemplateRenderer and SlotRenderer so we can reuse the schemas defined in uischemas.json (also provided in the tabs to be viewed and edited - of course the tester is a string version of the JS function although for the Template/Slot renderers this is no needed but for the Root Object demo I'm showing how we can use the tester function.

Please review and if possible I would liked to include this into the final release 

Check the Template/Slot renderer demo https://deploy-preview-86--jsonforms-vuetify-renderers.netlify.app/#/example/template-slot

**Comment by sdirix** [comment]
> Please review and if possible I would liked to include this into the final release

Thanks for all your contributions. We'll take a look as soon as possible for us. We now did the 3.0 release as the main packages are already released for a while and we should not trail too much behind.

However going forward we plan to stable release more often than before, so the changes in the pipeline don't need to wait for a year for a stable release.

**Comment by kchobantonov** [comment]
@lucas-koehler will you have time to review this PR as well as the one for the file support before we release ? @sdirix  are you planning to include those 2 open PRs before releasing the next version or you want to release with the changes for the controls which was merged already and later on have another release if you need more time to review and consider those 2 PRs?

**Comment by sdirix** [comment]
HI @kchobantonov, I just released the `3.1.0-alpha.0` version of the renderer set which also aligns it again with the other packages which were already released as `3.1.0-alpha.0`.

Next I would like to suggest that we take a look at the file renderer PR. However that will not happen before January 2023.

Regarding the template renderers I'm still not sure whether it makes sense to add them to the base JSON Forms Vuetify renderer set. As discussed previously, the use case is not really a core use case of the renderer set nor do we use the feature ourselves. The template renderers are probably most useful in the webcomponent variant of the renderer set as it's not easy to add custom renderers there. You might want to consider including them in the webcomponent release and/or releasing them standalone.

**Pull request closed without merging**
